### ISSUE TITLE
Add new languages to hangman

### ISSUE THREAD

**Issue by floppylab** [floppylab/clean-code#1]
Feel free to add a new language to the list. Please try to keep the original mistakes, structure, so that everyone can work on the "exact same" bugs, making similar improvements.

Before you start working on a language, please leave a comment here. I will merge PRs only from people who made comments. :)

**Comment by hima-Megahed** [comment]
Hello, I'll be happy to contribute I'll start with C#. @leonorader @floppylab

**Comment by lpegoraro** [comment]
Hey, I'll be happy to contribute. I will use `Groovy`. @floppylab

**Comment by xforever1313** [comment]
I'd like to contribute too!  I'll use C++.

**Comment by jwdjj** [comment]
I'd like to contribute to write this in Go lang!

**Comment by kennedy** [comment]
I will contribute python3!

**Comment by jwdjj** [comment]
> I'd like to contribute to write this in Go lang!

#9 Go implementation

**Comment by ywpark1** [comment]
I'd like to work on this with JavaScript.

**Comment by floppylab** [comment]
I created separate issues for each language. :)
